---
# (c) Copyright: David HEURTEVENT, 2024
# License: GPL 3.0
# tasks file for autoremove

# RedHat
- block:

  # should be equivalent to dnf autoremove
  - name: Autoremove unneeded packages installed as dependencies
    ansible.builtin.dnf:
      autoremove: yes

  when: ansible_os_family == 'RedHat'