---
# (c) Copyright: David HEURTEVENT, 2024
# License: GPL 3.0
# tasks file for remove

- block:
  - name: Set package if not specified
    pause:
      prompt: "Enter the package name" 
    register: package_prompt
  - set_fact: 
      package: "{{ package_prompt.user_input }}"
  when: package is not defined

# RedHat
- block:

  - block:
    #sudo dnf remove -y [package]
    - name: "DNF remove {{ package }}"
      become: true
      ansible.builtin.dnf:
        name:
          - "{{ package }}"
        state: absent
  
  when: ansible_os_family == 'RedHat'