---
# (c) Copyright: David HEURTEVENT, 2024
# License: GPL 3.0
# tasks file for install_repo

- block:
  - name: Set the RPM url if not specified
    pause:
      prompt: "Enter the url of the repo (must be a rpm package)" 
    register: url_prompt
  - set_fact: 
      rpmurl: "{{ url_prompt.user_input }}"
  - name: Fail if file extension is not .rpm
    fail:
      msg: "File extension is not .rpm"
    when: rpmurl.split('.')[-1] != 'rpm'
  when: rpmurl is not defined

- block:
  - name: Fail if file extension is not .rpm
    fail:
      msg: "File extension is not .rpm"
    when: rpmurl.split('.')[-1] != 'rpm'
  when: rpmurl is defined

# RedHat
- block:  

  # dnf install RPMURL
  - name: 'install repo'
    become: true
    ansible.builtin.command:
      cmd: "dnf install {{ rpmurl }}"

  when: ansible_os_family == 'RedHat'